feat(*): typescript prettier vitest
americanexpress/vitruvius pull request #57
Opened 2024-11-13 00:44 UTC by code-forger

Convert this codebase to typescript (from js), prettier (from nothing) and vitest (from jest)

2024-11-13 00:51 UTC, code-forger commented on README.md
>  ```
I will add the new documentation for how to use this library with typescript before this PR can be merged

2024-11-13 00:51 UTC, code-forger commented on __tests__/fixtures.ts
> +export function runVitruviusImmutableTests(
Its a shame that this function is bifurcated for the sake of the two different type of Vitruvius. However the gymnastics that would be required to do this in a single function like it was before are not worth it for a test file.

2024-11-13 00:51 UTC, code-forger commented on __tests__/fixtures.js
> -      const store = configureStore({ reducer }, reducer.buildInitialState(locals));
Note, this test did not make it into the other file because TS does not allow it. This is because `configureStore` expects 1 parameter and we are passing 2. I can not find any reference online to this function ever taking 2 parameters.

2024-11-13 00:51 UTC, code-forger commented on src/immutable.ts
> +type VitruviusImmutableOptionalCombinedReducer<Locals> = ReturnType<typeof combineReducers> & {
Ironically, the use of `ReturnType<typeof combineReducers>` actually weakens the types of vitruvius. This is because redux-immutable does not preserve the types of the combined reducers. Therefore when using the immutable variation of vitruvius, callers will not be able to rely on typescript when accessing the resultant store.

I looked briefly into preserving the types of the reducers within vitruvius itself, but it is extremely complex. I recommend we proceed with the above types, and re-visit this hole in the type chain later.

2024-11-13 14:14 UTC, guym4c approved these changes, later dismissed

2024-11-13 14:21 UTC, smackfu reviewed
Need to circle back to review the code more.

2024-11-13 14:21 UTC, smackfu commented on vitest.config.js
> +import { defineConfig } from 'vitest/config';
Maybe make this a typescript file?

2024-11-13 14:21 UTC, smackfu commented on package.json
>    "main": "lib/index.js",
Think we need to add a types key.

2024-11-13 14:21 UTC, smackfu commented on package.json
> +    "test:unit": "npm run build --ignore-scripts && vitest --run",
Can you make the build a "pretest:unit" script?

2024-11-13 14:21 UTC, smackfu commented on package.json
> +    "typescript": "^5.4.4",
Typescript doesn't follow semver because every change is breaking.
```suggestion
    "typescript": ">=5.4.4",
```

2024-11-13 14:23 UTC, smackfu commented on vitest.config.js
I wonder why this file didn't get flagged by the issue this PR fixes:
https://github.com/americanexpress/eslint-config-amex/pull/130

2024-11-13 14:24 UTC, smackfu commented on vitest.config.js
Oh, I guess it matches this by accident:
```
'**/*{.,_}{test,spec}.{js,jsx}',
```

2024-11-13 14:57 UTC, Matthew-Mallimo commented on tsconfig.json
> +    "jsx": "react",
```suggestion
    "jsx": "react",
```

Is this needed? this package doesn't contain any react code

2024-11-13 14:59 UTC, Matthew-Mallimo commented on .github/workflows/release-please.yml
shouldn't this include a build step now?

2024-11-13 15:04 UTC, zacowan commented on package.json
> +    "typescript": "^5.4.4",
Perhaps `~`? Or are even patch versions breaking?

2024-11-13 15:07 UTC, smackfu commented on package.json
> +    "typescript": "^5.4.4",
Yeah since it's a dev dep it honestly doesn't really matter.

2024-11-13 18:52 UTC, 10xLaCroixDrinker commented on .babelrc
> +  "plugins": ["@babel/plugin-transform-typescript"]
Does babel-preset-amex need TS support?

e.g.

```json
{
  "presets": ["amex/ts"]
}
```

2024-11-13 19:32 UTC, 10xLaCroixDrinker requested changes

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on .eslintrc.json
> +  "plugins": ["@typescript-eslint"],
Can we add a ts dir to the eslint config like we did for prettier?

I think that updating the eslint config with TS support should block this PR

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on .github/workflows/release-please.yml
We already had an existing build step, its covered by:

```
"prepublishOnly": "npm run build",
```

Though, personally, I prefer `prepack` over `prepublishOnly`

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on .gitignore
> +coverage
Is there an `.npmignore` that also needs updating?

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on __tests__/__snapshots__/index.spec.ts.snap
> -exports[`vitruvius should return an initialState that is acceptable to redux toolkit's configureStore 1`] = `
Intentionally deleted snapshot?

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on __tests__/collectBuiltState.spec.ts
> +      defaultState: Map(),
👀

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on __tests__/fixtures.js
> -      const store = configureStore({ reducer }, reducer.buildInitialState(locals));
I think it should be:

```js
const store = configureStore({ 
  reducer,
  preloadedState: reducer.buildInitialState(locals)
});
```

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on __tests__/fixtures.ts
> +export function runVitruviusImmutableTests(
aww, by TS overrides are sooooo fun 🤡

2024-11-13 19:32 UTC, 10xLaCroixDrinker commented on package.json
>      "test": "npm run test:lint && npm run test:unit",
Can we implement tsd and test our types?

e.g. https://github.com/pinojs/pino-abstract-transport/blob/main/test/types/index.test-d.ts

2024-11-13 19:34 UTC, 10xLaCroixDrinker commented
A little feedback on the commit message. It is debatable whether this is a feature, but if it is, only the addition of types is a feature and that's all that should be in the head of the message. Details about refactors and tests should be in the body. This will make for a better changelog upon release

2024-11-13 19:36 UTC, smackfu commented on .eslintignore
> +vitest.config.js
Aha! That's why it didn't run into this issue:
https://github.com/americanexpress/eslint-config-amex/pull/130

2024-11-13 20:18 UTC, 10xLaCroixDrinker commented on .babelrc
> +  "plugins": ["@babel/plugin-transform-typescript"]
honestly, we maybe don't even need a separate file. could just use overrides for `.ts` and `.tsx`

2024-11-13 20:19 UTC, 10xLaCroixDrinker commented on vitest.config.js
I don't think this repo has consumed the update

2024-11-13 20:19 UTC, 10xLaCroixDrinker commented on vitest.config.js
This file is being ignored currently

https://github.com/americanexpress/vitruvius/pull/57#discussion_r1841003857

2024-12-10 11:43 UTC, code-forger commented on __tests__/fixtures.js
> -      const store = configureStore({ reducer }, reducer.buildInitialState(locals));
you are right

2024-12-10 11:43 UTC, code-forger commented on __tests__/__snapshots__/index.spec.ts.snap
> -exports[`vitruvius should return an initialState that is acceptable to redux toolkit's configureStore 1`] = `
https://github.com/americanexpress/vitruvius/pull/57/files/785fd5ee76a0bcf178d917640bb6905e8a9c0d79#r1841030458

restored now that this test has been restored as per your suggestion

2024-12-10 11:43 UTC, code-forger commented on package.json
>      "test": "npm run test:lint && npm run test:unit",
The idea is that the types are implicitly tested by the incredibly strict configuration we have for tsc and eslint.

I would be happy to investigate tsd as a follow up piece of work

2024-12-10 11:46 UTC, code-forger commented
@10xLaCroixDrinker 

> A little feedback on the commit message....

did an amend to fix, look good now?

2024-12-10 11:46 UTC, code-forger commented on __tests__/__snapshots__/index.spec.ts.snap
> -exports[`vitruvius should return an initialState that is acceptable to redux toolkit's configureStore 1`] = `
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:46 UTC, code-forger commented on .gitignore
> +coverage
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:46 UTC, code-forger commented on package.json
>      "coveralls": "^3.1.1",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:46 UTC, code-forger commented on package.json
>      "eslint-plugin-jest": "^27.6.3",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:46 UTC, code-forger commented on package.json
> +    "rimraf": "^5.0.5",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:46 UTC, code-forger commented on package.json
>      "clean": "rimraf lib",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:47 UTC, code-forger commented on package.json
>      "eslint-config-amex": "^16.0.0",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:47 UTC, code-forger commented on .eslintignore
> +vitest.config.js
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:47 UTC, code-forger commented on vitest.config.js
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:47 UTC, code-forger commented on package.json
> +    "typescript": "^5.4.4",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:47 UTC, code-forger commented on package.json
>    "main": "lib/index.js",
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-10 11:47 UTC, code-forger commented on vitest.config.js
> +import { defineConfig } from 'vitest/config';
addressed in [f04d16d](https://github.com/americanexpress/vitruvius/commit/f04d16dcc861948b2ea96c64c987dda8dd8c7c75)

2024-12-11 16:58 UTC, smackfu commented on .github/workflows/release-please.yml
Yes, I would suggest `prepack`.  Otherwise when you run `npm pack` it doesn't rebuild.

2024-12-11 17:05 UTC, smackfu commented
@code-forger this isn't working for me.  I'm not getting the types in the package:

<img width="291" alt="Screenshot 2024-12-11 at 12 04 09 PM" src="https://github.com/user-attachments/assets/be94c751-0470-4bb4-bb23-8aa6eb87ff7b" />

As a result getting this error:
```
src/ducks.ts:1:29 - error TS7016: Could not find a declaration file for module '@americanexpress/vitruvius/immutable'.
```

2024-12-12 12:50 UTC, code-forger commented
@smackfu an `npm run build` produces this output for me 
<img width="259" alt="image" src="https://github.com/user-attachments/assets/9dce04dd-ce17-4a4e-9f9b-2072eb2991ac" />

2024-12-16 09:44 UTC, code-forger commented
@smackfu i tested with pack, this was an npm ignore issue, fixed in [7e83db3](https://github.com/americanexpress/vitruvius/pull/57/commits/7e83db368babc784376372de3cd85f22d963f293)

2025-02-17 10:32 UTC, closed without merging